name: Quality

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup linting
        uses: ./.github/actions/setup

      - name: Lint - TypeScript
        run: pnpm --filter @commercetools/commerce-agent run lint

      - name: Lint - Model Context Protocol
        run: pnpm --filter @commercetools/commerce-mcp run lint

  formatting:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup formatting
        uses: ./.github/actions/setup

      - name: Prettier - TypeScript
        run: pnpm --filter @commercetools/commerce-agent run prettier-check

      - name: Prettier - Model Context Protocol
        run: pnpm --filter @commercetools/commerce-mcp run prettier-check

  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup testing
        uses: ./.github/actions/setup

      - name: Test - TypeScript
        run: pnpm --filter @commercetools/commerce-agent run test

      - name: Test - Model Context Protocol
        run: |
          # Builds types which are neededin tests
          pnpm --filter @commercetools/commerce-agent run build
          pnpm --filter @commercetools/commerce-mcp run test

  building:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup testing
        uses: ./.github/actions/setup

      - name: Test - TypeScript
        run: |
          pnpm --filter @commercetools/commerce-agent run build
          pnpm --filter @commercetools/commerce-agent run clean

      - name: Test - Model Context Protocol
        run: |
          pnpm --filter @commercetools/commerce-mcp run build
          pnpm --filter @commercetools/commerce-mcp run clean
